### ISSUE TITLE
In-app browser closes on app re-entry

### ISSUE THREAD

**Issue by mineiwik** [netbirdio/android-client#27]
On the first start of the app, one has to log in to an account, either to one hosted at Netbird itself or to a self-hosted one. Now as I use a password manager I have to temporarily switch the app to grab the user credentials. However, when I re-enter the Netbird Android app to paste the credentials, the in-app browser closes instantaneously.

**Comment by czadikem** [comment]
I am having this same issue, after getting logged in by not using my password manager, I had to temporarily disable MFA as this issue effects me being able to login after 24hrs on that device.

**Comment by mannp** [comment]
This and the inability to use setup keys makes the android app unusable for me, which is a real shame, as I am loving the other parts of netbird.
